### ISSUE TITLE
The letter e is removed from all of my strings

### ISSUE THREAD

**Issue by devkinetic** [pedro-hs/checkbox.sh#12]
Using the latest version

```
test="test|test2"
./lib/checkbox.sh --options="$test" --multiple --message="Select"
```

**Result**
```
 Select
--------------------------------------------------
    [ ] tst
    [ ] tst2
--------------------------------------------------
  1/2  |  0 selected

```

**Comment by pedro-hs** [comment]
Thanks @devkinetic!
If you have another problem let me know, by the way I will close this issue

Fixed in this commit: https://github.com/pedro-hs/checkbox.sh/commit/593b369d56d5c09d247861eca8dfea8637bce294
Solved by keeping just the C ascii signs
I have tested the others ascii signs and it's working

![image](https://user-images.githubusercontent.com/42540954/133671831-1bbd2b52-00ca-4f12-b606-e8a932498c8e.png)

<strong>⭐ If you like this software, please, give a star ⭐</strong>

**Comment by devkinetic** [comment]
Yes that worked great! I saw you added fix OSX bug, is that related to directly/indirectly to this fix? I haven't tested my script on a mac yet.

**Comment by pedro-hs** [comment]
Nice @devkinetic

Not really, I have searched the ASCII signs in another site, but some of signs are unnecessary, so I changed to C ASCII signs, which looks like more compatible with bash strings

Until now, the script don't work properly on mac, I have made some tries to fix, but I need to test the script in mac and I have some problems accessing from AWS, but as soon as possible I will work on that task of keep script running in mac and linux
